# Table Of Contents

- [Reading a csv file](#Reading-from-a-csv-file)
- [Quick Summary Statistics](#Quick-Summary-Statistics)
- [Sorting on One Column](#Sorting-on-One-Column)
- [Removing duplicates](#Removing-duplicates)
- [Finding duplicates](#Finding-duplicates)

## Reading from a csv file

[Back to Top](#Table-Of-Contents)

In [5]:
!head -n 5 cuts.csv

ï»¿Year,Month,Month_Number,Data_Item,Value,Units,Source
2024,August,8,Ground chuck retail price,5.638,Dollars per pound,BLS
2024,September,9,Ground chuck retail price,5.576,Dollars per pound,BLS
2024,October,10,Ground chuck retail price,5.586,Dollars per pound,BLS
2024,November,11,Ground chuck retail price,5.605,Dollars per pound,BLS

In [1]:
import polars as pl

df = pl.read_csv(
    "cuts.csv"            
)

In [2]:
df.head()

shape: (5, 7)
┌──────┬───────────┬──────────────┬───────────────────────────┬───────┬───────────────────┬────────┐
│ Year ┆ Month     ┆ Month_Number ┆ Data_Item                 ┆ Value ┆ Units             ┆ Source │
│ ---  ┆ ---       ┆ ---          ┆ ---                       ┆ ---   ┆ ---               ┆ ---    │
│ i64  ┆ str       ┆ i64          ┆ str                       ┆ str   ┆ str               ┆ str    │
╞══════╪═══════════╪══════════════╪═══════════════════════════╪═══════╪═══════════════════╪════════╡
│ 2024 ┆ August    ┆ 8            ┆ Ground chuck retail price ┆ 5.638 ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ September ┆ 9            ┆ Ground chuck retail price ┆ 5.576 ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ October   ┆ 10           ┆ Ground chuck retail price ┆ 5.586 ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ November  ┆ 11           ┆ Ground chuck retail price ┆ 5.605 ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ December  ┆ 12           ┆ Ground chuck retail price ┆ 5.576 ┆ Dollars per pound ┆ BLS    │
└──────┴───────────┴──────────────┴───────────────────────────┴───────┴───────────────────┴────────┘

## Set the schema/data type of each column

[Back to Top](#Table-Of-Contents)

`schema={key: value}` is for ALL colunms, for a few columns, use `schema_overrides={key: value}`

In [13]:
df = pl.read_csv(
    "cuts.csv",
    schema={
        "Year": pl.Int32,
        "Month": pl.String,
        "Month_Number": pl.Int32,
        "Data_Item": pl.String,
        "Value": pl.Float32,
        "Units": pl.String,
        "Source": pl.String
    },
    null_values="NA",
)

In [14]:
df.head()

shape: (5, 7)
┌──────┬───────────┬──────────────┬───────────────────────────┬───────┬───────────────────┬────────┐
│ Year ┆ Month     ┆ Month_Number ┆ Data_Item                 ┆ Value ┆ Units             ┆ Source │
│ ---  ┆ ---       ┆ ---          ┆ ---                       ┆ ---   ┆ ---               ┆ ---    │
│ i32  ┆ str       ┆ i32          ┆ str                       ┆ f32   ┆ str               ┆ str    │
╞══════╪═══════════╪══════════════╪═══════════════════════════╪═══════╪═══════════════════╪════════╡
│ 2024 ┆ August    ┆ 8            ┆ Ground chuck retail price ┆ 5.638 ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ September ┆ 9            ┆ Ground chuck retail price ┆ 5.576 ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ October   ┆ 10           ┆ Ground chuck retail price ┆ 5.586 ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ November  ┆ 11           ┆ Ground chuck retail price ┆ 5.605 ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ December  ┆ 12           ┆ Ground chuck retail price ┆ 5.576 ┆ Dollars per pound ┆ BLS    │
└──────┴───────────┴──────────────┴───────────────────────────┴───────┴───────────────────┴────────┘

## Quick Summary Statistics

[Back to Top](#Table-Of-Contents)

In [16]:
df.shape    # (rows, columns), e.g. (1000, 8)

(800, 7)

In [17]:
df.height   # number of rows

800

In [18]:
len(df)     # also the number of rows

800

In [19]:
df.width    # number of columns

7

In [20]:
df.schema

Schema([('Year', Int32),
        ('Month', String),
        ('Month_Number', Int32),
        ('Data_Item', String),
        ('Value', Float32),
        ('Units', String),
        ('Source', String)])

In [21]:
df.columns

['Year', 'Month', 'Month_Number', 'Data_Item', 'Value', 'Units', 'Source']

In [22]:
df.null_count()

shape: (1, 7)
┌──────┬───────┬──────────────┬───────────┬───────┬───────┬────────┐
│ Year ┆ Month ┆ Month_Number ┆ Data_Item ┆ Value ┆ Units ┆ Source │
│ ---  ┆ ---   ┆ ---          ┆ ---       ┆ ---   ┆ ---   ┆ ---    │
│ u32  ┆ u32   ┆ u32          ┆ u32       ┆ u32   ┆ u32   ┆ u32    │
╞══════╪═══════╪══════════════╪═══════════╪═══════╪═══════╪════════╡
│ 0    ┆ 0     ┆ 0            ┆ 0         ┆ 31    ┆ 0     ┆ 0      │
└──────┴───────┴──────────────┴───────────┴───────┴───────┴────────┘

In [23]:
df.glimpse()

Rows: 800
Columns: 7
$ Year         <i32> 2024, 2024, 2024, 2024, 2024, 2025, 2025, 2025, 2025, 2025
$ Month        <str> 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March', 'April', 'May'
$ Month_Number <i32> 8, 9, 10, 11, 12, 1, 2, 3, 4, 5
$ Data_Item    <str> 'Ground chuck retail price', 'Ground chuck retail price', 'Ground chuck retail price', 'Ground chuck retail price', 'Ground chuck retail price', 'Ground chuck retail price', 'Ground chuck retail price', 'Ground chuck retail price', 'Ground chuck retail price', 'Ground chuck retail price'
$ Value        <f32> 5.638000011444092, 5.576000213623047, 5.585999965667725, 5.605000019073486, 5.576000213623047, 5.494999885559082, 5.74399995803833, 5.854000091552734, 5.995999813079834, 6.01800012588501
$ Units        <str> 'Dollars per pound', 'Dollars per pound', 'Dollars per pound', 'Dollars per pound', 'Dollars per pound', 'Dollars per pound', 'Dollars per pound', 'Dollars per pound', 'Dollars per pound', 'Dollars per pound'
$ Source       <str> 'BLS', 'BLS', 'BLS', 'BLS', 'BLS', 'BLS', 'BLS', 'BLS', 'BLS', 'BLS'

## Sorting on One Column

[Back to Top](#Table-Of-Contents)

In [26]:
df.sort("Month", descending=True)

shape: (800, 7)
┌──────┬───────────┬──────────────┬─────────────────────────────────┬───────┬─────────────────────────┬────────┐
│ Year ┆ Month     ┆ Month_Number ┆ Data_Item                       ┆ Value ┆ Units                   ┆ Source │
│ ---  ┆ ---       ┆ ---          ┆ ---                             ┆ ---   ┆ ---                     ┆ ---    │
│ i32  ┆ str       ┆ i32          ┆ str                             ┆ f32   ┆ str                     ┆ str    │
╞══════╪═══════════╪══════════════╪═════════════════════════════════╪═══════╪═════════════════════════╪════════╡
│ 2024 ┆ September ┆ 9            ┆ Ground chuck retail price       ┆ 5.576 ┆ Dollars per pound       ┆ BLS    │
│ 2025 ┆ September ┆ 9            ┆ Ground chuck retail price       ┆ 6.326 ┆ Dollars per pound       ┆ BLS    │
│ 2024 ┆ September ┆ 9            ┆ Ground beef retail price        ┆ 5.67  ┆ Dollars per pound       ┆ BLS    │
│ 2025 ┆ September ┆ 9            ┆ Ground beef retail price        ┆ 6.323 ┆ Dollars per pound       ┆ BLS    │
│ 2024 ┆ September ┆ 9            ┆ Lean & extra lean ground beef … ┆ 7.223 ┆ Dollars per pound       ┆ BLS    │
│ …    ┆ …         ┆ …            ┆ …                               ┆ …     ┆ …                       ┆ …      │
│ 2026 ┆ April     ┆ 4            ┆ American processed cheese reta… ┆ 4.69  ┆ Dollars per pound       ┆ BLS    │
│ 2025 ┆ April     ┆ 4            ┆ Cheddar cheese, natural retail… ┆ 5.743 ┆ Dollars per pound       ┆ BLS    │
│ 2026 ┆ April     ┆ 4            ┆ Cheddar cheese, natural retail… ┆ 6.029 ┆ Dollars per pound       ┆ BLS    │
│ 2025 ┆ April     ┆ 4            ┆ Ice cream, prepackaged  retail… ┆ 6.229 ┆ Dollars per half gallon ┆ BLS    │
│ 2026 ┆ April     ┆ 4            ┆ Ice cream, prepackaged  retail… ┆ 6.24  ┆ Dollars per half gallon ┆ BLS    │
└──────┴───────────┴──────────────┴─────────────────────────────────┴───────┴─────────────────────────┴────────┘

## Sorting on Multiple Columns

In [28]:
df.sort(["Year","Month_Number"], descending=[False, True])

shape: (800, 7)
┌──────┬──────────┬──────────────┬─────────────────────────────────┬────────────┬───────────────────┬────────┐
│ Year ┆ Month    ┆ Month_Number ┆ Data_Item                       ┆ Value      ┆ Units             ┆ Source │
│ ---  ┆ ---      ┆ ---          ┆ ---                             ┆ ---        ┆ ---               ┆ ---    │
│ i32  ┆ str      ┆ i32          ┆ str                             ┆ f32        ┆ str               ┆ str    │
╞══════╪══════════╪══════════════╪═════════════════════════════════╪════════════╪═══════════════════╪════════╡
│ 2024 ┆ December ┆ 12           ┆ Eggs, Grade A large retail pri… ┆ 4.146      ┆ Dollars per dozen ┆ BLS    │
│ 2024 ┆ December ┆ 12           ┆ All other pork excluding canne… ┆ 3.656      ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ December ┆ 12           ┆ Retail broiler composite        ┆ 243.399994 ┆ Cents per pound   ┆ ERS    │
│ 2024 ┆ December ┆ 12           ┆ All ham (not canned or sliced)… ┆ 4.406      ┆ Dollars per pound ┆ BLS    │
│ 2024 ┆ December ┆ 12           ┆ Ground chuck retail price       ┆ 5.576      ┆ Dollars per pound ┆ BLS    │
│ …    ┆ …        ┆ …            ┆ …                               ┆ …          ┆ …                 ┆ …      │
│ 2026 ┆ January  ┆ 1            ┆ Pork chops, center cut, bone i… ┆ 4.453      ┆ Dollars per pound ┆ BLS    │
│ 2026 ┆ January  ┆ 1            ┆ Wholesale broiler composite     ┆ 85.699997  ┆ Cents per pound   ┆ ERS    │
│ 2026 ┆ January  ┆ 1            ┆ Beef for stew, boneless retail… ┆ 8.463      ┆ Dollars per pound ┆ BLS    │
│ 2026 ┆ January  ┆ 1            ┆ Chicken, fresh whole retail pr… ┆ 2.041      ┆ Dollars per pound ┆ BLS    │
│ 2026 ┆ January  ┆ 1            ┆ All uncooked ground beef retai… ┆ 6.868      ┆ Dollars per pound ┆ BLS    │
└──────┴──────────┴──────────────┴─────────────────────────────────┴────────────┴───────────────────┴────────┘

## Removing duplicates

[Back to Top](#Table-Of-Contents)

In [32]:
df = pl.DataFrame(
    {
        'k1': ['one'] * 3 + ['two'] * 4,
         'k2': [3, 2, 1, 3, 3, 4, 4]
    },
    schema={
        "k1": pl.String,
        "k2": pl.Int32,
    }
)

In [36]:
df

shape: (7, 2)
┌─────┬─────┐
│ k1  ┆ k2  │
│ --- ┆ --- │
│ str ┆ i32 │
╞═════╪═════╡
│ one ┆ 3   │
│ one ┆ 2   │
│ one ┆ 1   │
│ two ┆ 3   │
│ two ┆ 3   │
│ two ┆ 4   │
│ two ┆ 4   │
└─────┴─────┘

### Removing duplicates within one column

In [34]:
df.unique(subset="k1")

shape: (2, 2)
┌─────┬─────┐
│ k1  ┆ k2  │
│ --- ┆ --- │
│ str ┆ i32 │
╞═════╪═════╡
│ two ┆ 3   │
│ one ┆ 3   │
└─────┴─────┘

### Removing duplicates within multiple columns

In [35]:
df.unique(subset=["k1","k2"])

shape: (5, 2)
┌─────┬─────┐
│ k1  ┆ k2  │
│ --- ┆ --- │
│ str ┆ i32 │
╞═════╪═════╡
│ one ┆ 3   │
│ two ┆ 4   │
│ one ┆ 2   │
│ two ┆ 3   │
│ one ┆ 1   │
└─────┴─────┘

## Finding duplicates

[Back to Top](#Table-Of-Contents)

In [37]:
df.filter(pl.struct(["k1", "k2"]).is_duplicated())

shape: (4, 2)
┌─────┬─────┐
│ k1  ┆ k2  │
│ --- ┆ --- │
│ str ┆ i32 │
╞═════╪═════╡
│ two ┆ 3   │
│ two ┆ 3   │
│ two ┆ 4   │
│ two ┆ 4   │
└─────┴─────┘